default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog_development
  username: <%= ENV['DEV_USER'] %>
  password: <%= ENV['DEV_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test
  username: <%= ENV['TEST_USER'] %>
  password: <%= ENV['TEST_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['MOVIEDB_DATABASE_URL'] %>
  username: <%= ENV['MOVIEDB_DATABASE_DB'] %>
  password: <%= ENV['MOVIEDB_DATABASE_PASSWORD'] %>
