# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b227ea30755f899e52873bef6a7a0695b6340dc7aed61699cd1bb05985ece3b71ac65a2a3eb5c713a772432212dd696dba8d479e3f56f7dc40111281bb4f4471

test:
  secret_key_base: 427cb316eddbd6f65812322df11c2d080f6f35405fb16c9fdc02af4d4bf21eaeaf7f174db74832d0be2ca0f88441aa7363a9e698330ea9db3847678b783642c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
